### PR TITLE
Added routers to browserify fix

### PR DESCRIPTION
**Pull request by marksyzm**
Routers seemed to be missing, so I chucked them in with the build (I need them!)

### CODE REVIEW

**Comment by serapath** [comment]
coolio :-)

**Comment by marksyzm** [comment]
Must have been a nice coincidence that you worked on this exact fix the same day I was looking for it... I tried to get it working on my own fork and then your pull request popped up so I just went from there. Thanks!

**Comment by serapath** [comment]
its really a nice coincidence :-) I still have zero experience with joinJS, just figured it would be cool to use it for some diagramming of business processes.
The way it totally depends on stuff like jquery is quite annoying, but refactoring would take a lot of time.
The way i fixed it to work with browserify is also pretty generic and not well thought trough or optimized, but in the end, the library is big anyway and who cares for now :-)

**Comment by marksyzm** [comment]
Well, I can't see how else you'd do it other than the way you have. I see
that there was an ideal to join stuff up like a tree... but it makes it far
more complicated to read through the project as a whole and understand
what's where, plus it keeps most of the mess out of the files that are
using browserify.
I just hope soon they drop backbone + underscore + jquery dependency (maybe
just opt for lodash alone) or at least give the option - so their package
isn't so bloated.

**Comment by serapath** [comment]
that would be pretty awesome. ...btw, if you use it for a commercial project you might have resources to refactor it over time. I dont know, but for now, the original author doesnt seem to be very responsive.

**Comment by serapath** [comment]
btw. if you like to structure your projet in general more into a "component" style, then you could also give a project called [atomify](http://github.com/serapath/atomify) a try. A small technical presentation/tutorial can be found [here](http://serapath.github.io/atomify)

**Pull request merged**
